---
title: "lab5"
author: "Zihao Han"
date: "April 16, 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
acc <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/accident.csv", stringsAsFactors = FALSE)
weekacc <- function(x) {
    return(sum(acc$DAY_WEEK == x))
}
total = c(weekacc(1),weekacc(2),weekacc(3),weekacc(4),weekacc(5),weekacc(6),weekacc(7))
week = c(1:7)
df <- data.frame(total,week)
df
ggplot(df,aes(x= week, y=total)) + geom_col() + theme(axis.text.x = element_text(angle = 0, hjust = 1)) + xlab("Days of Week") + ylab("Amount of accidents happened") + ggtitle("Accidents happened on days")
```

From the plot, we can say that the accident amount is increasing from Thursday to Sunday and decrease from Sunday to Tuesday. SunDay got the most accidents of a week.

```{r}
houracc <- function(x) {
    return(sum(acc$HOUR == x))
}
totalh = c(houracc(0),houracc(1),houracc(2),houracc(3),houracc(4),houracc(5),houracc(6),houracc(7),houracc(8),houracc(9),houracc(10),houracc(11),houracc(12),houracc(13),houracc(14),houracc(15),houracc(16),houracc(17),houracc(18),houracc(19),houracc(20),houracc(21),houracc(22),houracc(23))
hour = c(0:23)
df2 <- data.frame(totalh,hour)
df2
ggplot(df2,aes(x= hour, y=totalh)) + geom_col() + theme(axis.text.x = element_text(angle = 0, hjust = 1)) + xlab("hours of day") + ylab("Amount of accidents happened") + ggtitle("Accidents happened on hours")
```

Most accident happened from 10am to 6pm.
```{r}
numOfdrunk = sum(acc$DRUNK_DR >= 1)
numOfdrunk
```

There are 8769 Accidents happened with at least one drunk driver.

```{r}
per <- read.csv("https://raw.githubusercontent.com/xdaiISU/ds202materials/master/hwlabs/fars2017/person.csv", stringsAsFactors = FALSE)
per
drivers <- subset(per,PER_TYP==1)
drivers

```

```{r}
dat<- full_join(acc,drivers)
str(dat)


```

```{r}
DAYWEEK<-dat%>%group_by(DAY_WEEK)%>%tally
DAYWEEK
HOUR<-dat%>%group_by(HOUR)%>%tally
SEX<-dat%>%group_by(SEX)%>%tally
SEX
a<-dat%>%group_by(DAY_WEEK,HOUR,SEX)%>%tally
a
ggplot(DAYWEEK,aes(x=DAY_WEEK,y=n))+geom_point()
ggplot(HOUR,aes(x=HOUR,y=n))+geom_point()
ggplot(SEX,aes(x=SEX,y=n))+geom_point()
```